routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\ProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [AuthController::class, 'showFormLogin'])->name('login');
Route::get('login', [AuthController::class, 'showFormLogin'])->name('login');
Route::post('login', [AuthController::class, 'login']);
Route::get('register', [AuthController::class, 'showFormRegister'])->name('register');
Route::post('register', [AuthController::class, 'register']);
 
Route::group(['middleware' => 'auth'], function () {
    // Route::get('home', [HomeController::class, 'index'])->name('home');
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
});

Route::group(['as'=>'admin.','prefix' => 'admin','middleware'=>['auth','admin']], function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('applications', [DashboardController::class, 'viewApplications'])->name('applications.index');
    Route::get('applications/{id}', [DashboardController::class, 'showApplications'])->name('applications.show');
    Route::patch('applications/accept/{application}', [DashboardController::class, 'acceptApplications'])->name('applications.accept');
    Route::patch('applications/decline/{application}', [DashboardController::class, 'declineApplications'])->name('applications.decline');
});

Route::group(['as'=>'user.','prefix' => 'user','middleware'=>['auth','user']], function () {
    Route::get('dashboard', [HomeController::class, 'index'])->name('dashboard');
    Route::resource('applications', ApplicationController::class);
    Route::post('get-classification', [ApplicationController::class, 'getClassification'])->name('get-classification.data');
    Route::get('print_pdf/{application}', [ApplicationController::class, 'printPdf'])->name('print_pdf');
    Route::get('profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('profile', [ProfileController::class, 'update'])->name('profile.update');
});

resources/views/admin/applications.blade.php
@extends('admin.layout')
 
@section('content')
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Daftar Pengajuan SKPI</a>
    <div class="d-flex align-items-center">
        <a href="{{  route('admin.dashboard') }}" class="btn btn-primary me-3">
            Back
        </a>
    </div>
  </div>
</nav>

<div class="card">
  <div class="card-body">   
  @if ($message = Session::get('success'))
      <div class="alert alert-success">
          <p>{{ $message }}</p>
      </div>
  @endif
  
  <ul class="nav nav-tabs" role="tablist" data-tabs="tabs">
    <li class="nav-item">
      <a class="nav-link active" href="#pending" role="tab" data-toggle="tab">Pending</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#accepted" role="tab" data-toggle="tab">Accepted</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#declined" role="tab" data-toggle="tab">Declined</a>
    </li>
  </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="pending">
        <table class="table table-bordered">
            <tr>
                <th>No</th>
                <th>User</th>
                <th>BEM</th>
                <th>Dekanat</th>
                <th width="280px">Action</th>
            </tr>
            @foreach ($applications_pending as $application)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $application->name }}</td>
                <td>
                @if ($application->bem_confirmed == 1)
                    <i class="fas fa-check"></i>
                @elseif ($application->bem_confirmed == 0)
                    <i class="fas fa-clock"></i>
                @else
                    <i class="fas fa-times"></i>
                @endif
                </td>
                <td>
                @if ($application->dekanat_confirmed == 1)
                    <i class="fas fa-check"></i>
                @elseif ($application->dekanat_confirmed == 0)
                    <i class="fas fa-clock"></i>
                @else
                    <i class="fas fa-times"></i>
                @endif
                </td>
                <td>
                    <!-- <form action="{{ route('user.applications.destroy',$application->id) }}" method="POST"> -->
                        <a class="btn btn-primary" href="{{ route('admin.applications.show',$application->id) }}">Show</a>

                        <form method="POST" action="{{ route('admin.applications.accept',$application->id) }}">
                          @csrf
                          @method('patch')
                          <button type="submit" class="btn btn-success">Accept</button>
                        </form>

                        <form method="POST" action="{{ route('admin.applications.decline',$application->id) }}">
                          @csrf
                          @method('patch')
                          <button type="submit" class="btn btn-danger">Decline</button>
                        </form>

                        @csrf
                        <!-- @method('DELETE') -->

                        <!-- <button type="submit" class="btn btn-danger">Delete</button> -->
                    <!-- </form> -->
                </td>
            </tr>
            @endforeach
        </table>

        {!! $applications_pending->fragment('pending')->links("pagination::bootstrap-4") !!}
      </div>
      <div role="tabpanel" class="tab-pane" id="accepted">
        <table class="table table-bordered">
            <tr>
                <th>No</th>
                <th>User</th>
                <th>BEM</th>
                <th>Dekanat</th>
                <th width="280px">Action</th>
            </tr>
            @foreach ($applications_accepted as $application)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $application->name }}</td>
                <td>
                @if ($application->bem_confirmed == 1)
                    <i class="fas fa-check"></i>
                @elseif ($application->bem_confirmed == 0)
                    <i class="fas fa-clock"></i>
                @else
                    <i class="fas fa-times"></i>
                @endif
                </td>
                <td>
                @if ($application->dekanat_confirmed == 1)
                    <i class="fas fa-check"></i>
                @elseif ($application->dekanat_confirmed == 0)
                    <i class="fas fa-clock"></i>
                @else
                    <i class="fas fa-times"></i>
                @endif
                </td>
                <td>
                    <!-- <form action="{{ route('user.applications.destroy',$application->id) }}" method="POST"> -->
                        <a class="btn btn-primary" href="{{ route('admin.applications.show',$application->id) }}">Show</a>

                        <form method="POST" action="{{ route('admin.applications.accept',$application->id) }}">
                          @csrf
                          @method('patch')
                          <button type="submit" class="btn btn-success">Accept</button>
                        </form>

                        <form method="POST" action="{{ route('admin.applications.decline',$application->id) }}">
                          @csrf
                          @method('patch')
                          <button type="submit" class="btn btn-danger">Decline</button>
                        </form>

                        @csrf
                        <!-- @method('DELETE') -->

                        <!-- <button type="submit" class="btn btn-danger">Delete</button> -->
                    <!-- </form> -->
                </td>
            </tr>
            @endforeach
        </table>

        {!! $applications_accepted->fragment('accepted')->links("pagination::bootstrap-4") !!}
      </div>
      <div role="tabpanel" class="tab-pane" id="declined">
        <table class="table table-bordered">
            <tr>
                <th>No</th>
                <th>User</th>
                <th>BEM</th>
                <th>Dekanat</th>
                <th width="280px">Action</th>
            </tr>
            @foreach ($applications_declined as $application)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $application->name }}</td>
                <td>
                @if ($application->bem_confirmed == 1)
                    <i class="fas fa-check"></i>
                @elseif ($application->bem_confirmed == 0)
                    <i class="fas fa-clock"></i>
                @else
                    <i class="fas fa-times"></i>
                @endif
                </td>
                <td>
                @if ($application->dekanat_confirmed == 1)
                    <i class="fas fa-check"></i>
                @elseif ($application->dekanat_confirmed == 0)
                    <i class="fas fa-clock"></i>
                @else
                    <i class="fas fa-times"></i>
                @endif
                </td>
                <td>
                    <!-- <form action="{{ route('user.applications.destroy',$application->id) }}" method="POST"> -->
                        <a class="btn btn-primary" href="{{ route('admin.applications.show',$application->id) }}">Show</a>

                        <form method="POST" action="{{ route('admin.applications.accept',$application->id) }}">
                          @csrf
                          @method('patch')
                          <button type="submit" class="btn btn-success">Accept</button>
                        </form>

                        <form method="POST" action="{{ route('admin.applications.decline',$application->id) }}">
                          @csrf
                          @method('patch')
                          <button type="submit" class="btn btn-danger">Decline</button>
                        </form>

                        @csrf
                        <!-- @method('DELETE') -->

                        <!-- <button type="submit" class="btn btn-danger">Delete</button> -->
                    <!-- </form> -->
                </td>
            </tr>
            @endforeach
        </table>

        {!! $applications_declined->fragment('declined')->links("pagination::bootstrap-4") !!}
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  if(window.location.hash) {
    document.querySelector('.active').classList.remove('active');
    document.querySelector('[href="'+window.location.hash+'"]').classList.add('active');
    document.querySelector('.tab-pane').classList.remove('active');
    document.querySelector('[id="'+window.location.hash.replace('#', '')+'"]').classList.add('active');
  }
</script>
@endsection

resources/views/admin/applications_show.blade.php
@extends('admin.layout')
  
@section('content')
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Detail Pengajuan SKPI</a>
    <div class="d-flex align-items-center">
        <a href="{{ route('admin.applications.index') }}" class="btn btn-primary me-3">
            Back
        </a>
    </div>
  </div>
</nav>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama:</strong>
                {{ $application->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>NPM:</strong>
                {{ $application->npm }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Konfirmasi BEM:</strong>
                @if ($application->bem_confirmed == 1)
                    Disetujui
                @elseif ($application->bem_confirmed == 0)
                    Pending
                @else
                    Ditolak
                @endif
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Konfirmasi Dekanat:</strong>
                @if ($application->dekanat_confirmed == 1)
                    Disetujui
                @elseif ($application->dekanat_confirmed == 0)
                    Pending
                @else
                    Ditolak
                @endif
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Data Dukung:</strong>
            </div>
        </div>
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="pending">
            <table class="table table-bordered">
                <tr>
                    <th>No</th>
                    <th>Aktivitas</th>
                    <th>Klasifikasi</th>
                    <th>File</th>
                </tr>
                @foreach ($support_datas as $item)
                <tr>
                    <td>{{ ++$i }}</td>
                    <td>{{ $item->activity }}</td>
                    <td>{{ $item->classification }}</td>
                    <td><a href="{{ $item->full_file }}" target="_blank">{{ $item->file }}</a></td>
                </tr>
                @endforeach
            </table>
        </div>
    </div>
@endsection

resources/views/admin/home.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dashboard</title>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"> -->
    <!-- Font Awesome -->
        <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
      rel="stylesheet"
    />
</head>
<body>

<header>
  <!-- Intro settings -->
  <style>
    /* Default height for small devices */
    #intro-example {
      height: 400px;
    }

    /* Height for devices larger than 992px */
    @media (min-width: 992px) {
      #intro-example {
        height: 600px;
      }
    }
  </style>

  <!-- Navbar -->
  <!-- <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container-fluid">
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarExample01"
        aria-controls="navbarExample01"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarExample01">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item active">
            <a class="nav-link" aria-current="page" href="{{ route('user.dashboard') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('user.applications.index') }}">Pengajuan SKPI</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('user.profile.edit') }}">Profil</a>
          </li>
        </ul>
      </div>
    </div>
  </nav> -->
  <!-- Navbar -->

  <!-- Background image -->
  <div
    id="intro-example"
    class="p-5 text-center bg-image"
    style="background-image: url('http://kema.farmasi.unpad.ac.id/wp-content/uploads/2018/07/kemvlog.png');"
  >
    <div class="mask" style="background-color: rgba(0, 0, 0, 0.7);">
      <div class="d-flex justify-content-center align-items-center h-100">
        <div class="text-white">
          <h2 class="mb-3">Selamat datang di halaman dashboard</h2>
          <h1 class="mb-4">{{ Auth::user()->name }}</h1>
          <a
            class="btn btn-outline-light btn-lg m-2"
            href="{{ route('admin.dashboard') }}"
            role="button"
            rel="nofollow"
            >Home</a
          >
          <a
            class="btn btn-outline-light btn-lg m-2"
            href="{{ route('admin.applications.index') }}"
            role="button"
            rel="nofollow"
            >Pengajuan SKPI</a
          >
          <a
            class="btn btn-outline-light btn-lg m-2"
            href="{{ route('logout') }}"
            role="button"
            >Logout</a
          >
        </div>
      </div>
    </div>
  </div>
  <!-- Background image -->
</header>

<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
></script>
</body>
</html>

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Daftar Pengajuan SKPI</title>
    <!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet"> -->
    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
      rel="stylesheet"
    />
</head>
<body>
  
<div class="container">
    @yield('content')
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
<script>
$(function(){ 
    $('.nav-tabs a').on('click', function (e) {
        // e.preventDefault();
        $(this).tab('show');
    });  
});
</script>
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
></script>
</body>
</html>