routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\ApplicationController;
use App\Http\Controllers\ProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [AuthController::class, 'showFormLogin'])->name('login');
Route::get('login', [AuthController::class, 'showFormLogin'])->name('login');
Route::post('login', [AuthController::class, 'login']);
Route::get('register', [AuthController::class, 'showFormRegister'])->name('register');
Route::post('register', [AuthController::class, 'register']);
 
Route::group(['middleware' => 'auth'], function () {
    // Route::get('home', [HomeController::class, 'index'])->name('home');
    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
});

Route::group(['as'=>'admin.','prefix' => 'admin','middleware'=>['auth','admin']], function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('applications', [DashboardController::class, 'viewApplications'])->name('applications.index');
    Route::get('applications/{id}', [DashboardController::class, 'showApplications'])->name('applications.show');
    Route::patch('applications/accept/{application}', [DashboardController::class, 'acceptApplications'])->name('applications.accept');
    Route::patch('applications/decline/{application}', [DashboardController::class, 'declineApplications'])->name('applications.decline');
});

Route::group(['as'=>'user.','prefix' => 'user','middleware'=>['auth','user']], function () {
    Route::get('dashboard', [HomeController::class, 'index'])->name('dashboard');
    Route::resource('applications', ApplicationController::class);
    Route::post('get-classification', [ApplicationController::class, 'getClassification'])->name('get-classification.data');
    Route::get('print_pdf/{application}', [ApplicationController::class, 'printPdf'])->name('print_pdf');
    Route::get('profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('profile', [ProfileController::class, 'update'])->name('profile.update');
});

app/Models/Application.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Application extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id'
    ];
}

app/Http/Controllers/ApplicationController.php
<?php

namespace App\Http\Controllers;

use App\Models\Application;
use App\Models\SupportData;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use PDF;

class ApplicationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $applications = Application::join('users', 'users.id', '=', 'applications.user_id')
                        ->select('applications.*', 'users.name')
                        ->where('user_id', Auth::user()->id)
                        ->latest()
                        ->paginate(5);

        return view('applications.index',compact('applications'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        $activities = [
            ['id' => "PDK01",'activity' => "Penghargaan dan Kejuaraan Internasional"],
            ['id' => "PDK02",'activity' => "Penghargaan dan Kejuaraan Nasional"],
            ['id' => "PDK03",'activity' => "Penghargaan dan Kejuaraan Kota/Provinsi"],
            ['id' => "PDK04",'activity' => "Penghargaan dan Kejuaraan Universitas"],
            ['id' => "PDK05",'activity' => "Penghargaan dan Kejuaraan Fakultas"],
            ['id' => "ORG01",'activity' => "Organisasi Internasional"],
            ['id' => "ORG02",'activity' => "Organisasi Nasional"],
            ['id' => "ORG03",'activity' => "Organisasi Daerah"],
            ['id' => "ORG04",'activity' => "Organisasi Universitas"],
            ['id' => "ORG05",'activity' => "Organisasi Fakultas"],
            ['id' => "PNT01",'activity' => "Kepanitiaan Internasional"],
            ['id' => "PNT02",'activity' => "Kepanitiaan Nasional"],
            ['id' => "PNT03",'activity' => "Kepanitiaan Daerah"],
            ['id' => "PNT04",'activity' => "Kepanitiaan Universitas"],
            ['id' => "PNT05",'activity' => "Kepanitiaan Fakultas"],

            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],
            // ['id' => ,'activity' => ],

            // "Penguasaan Bahasa Asing",
            // "Sertifikasi profesi dan kompetensi",

            // "Karir dan kewirausahaan",

            // "Upacara Kenegaraan",

            // "Menulis Buku ISBN",

            // "Kontribusi Kegiatan Sosial",

            // "Asisten Proyek/Riset/Laboratorium",

            // "Pertukaran Mahasiswa",

            // "Pembicara Kegiatan",

            // "Peserta Seminar",

            // "Delegasi",

            // "Publikasi Ilmiah Internasional",
            // "Publikasi Ilmiah Nasional Terakreditasi",
            // "Publikasi Ilmiah Nasional Belum Terakreditasi",
            // "Publikasi Ilmiah Unpad",

            // "Artikel Media Massa",

            // "Pelatihan Kepemimpinan",

            // "Mawapres"
        ];
        return view('applications.create', [
            'user' => $user,
            'activities' => $activities
        ]);
    }

    public function getClassification(Request $request)
    {
        $id = $request->get('id');
        if ($id == "PDK01") {
            $classifications = [
                ["id" => $id, "classification" => "3 Besar"],
                ["id" => 2, "classification" => "Harapan atau Favorit"],
                ["id" => 3, "classification" => "Peserta"]
            ];
        } else {
            $classifications = [
                ["id" => 0, "classification" => "Nothing"],
            ];
        }
        return response()->json($classifications);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'addMoreInputFields.*.activity' => 'required',
            'addMoreInputFields.*.classification' => 'required',
            'addMoreInputFields.*.file' => 'required|file|max:2048'
            // 'name' => 'required',
            // 'detail' => 'required',
        ]);
    
        // Application::create($request->all());

        $application = new Application;
        $application->user_id = Auth::user()->id;
        $application->bem_confirmed = 0;
        $application->dekanat_confirmed = 0;
        $application->save();

        foreach ($request->addMoreInputFields as $key => $value) {
            
            $file = $value['file'];
            $filename = time()."_".$file->getClientOriginalName();
            $destination = 'application_file';
            $file->move($destination,$filename);

            SupportData::create([
                'activity' => $value['activity'],
                'classification' => $value['classification'],
                'grade' => 0,
                'file' => $filename,
                'application_id' => $application->id
            ]);
        }
     
        return redirect()->route('user.applications.index')
                        ->with('success','Pengajuan SKPI Baru Berhasil Dibuat.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Application  $application
     * @return \Illuminate\Http\Response
     */
    public function show(Application $application)
    {
        $application->name = Auth::user()->name;
        return view('applications.show',compact('application'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Application  $application
     * @return \Illuminate\Http\Response
     */
    public function edit(Application $application)
    {
        return view('applications.edit',compact('application'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Application  $application
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Application $application)
    {
        // $request->validate([
        //     'name' => 'required',
        //     'detail' => 'required',
        // ]);
    
        // $application->update($request->all());
    
        return redirect()->route('user.applications.index')
                        ->with('success','Pengajuan SKPI Berhasil Diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Application  $application
     * @return \Illuminate\Http\Response
     */
    public function destroy(Application $application)
    {
        $application->delete();
    
        return redirect()->route('user.applications.index')
                        ->with('success','Pengajuan Berhasil Dibatalkan');
    }

    public function printPdf(Application $application)
    {
        // $applications = Application::join('users', 'users.id', '=', 'applications.user_id')
        // ->select('applications.*', 'users.name')
        // ->get();

        $application->name = Auth::user()->name;
        $application->npm = Auth::user()->npm;
        $support_datas = SupportData::where('application_id', $application->id)->get();
    	$pdf = PDF::loadview('applications.skpi_pdf',[
            'application' => $application, 
            'support_datas' => $support_datas]);
    	// return $pdf->download('print-skpi-pdf');
        return $pdf->stream('print-skpi-pdf');
    }
}

resources/views/applications/create.blade.php
@extends('applications.layout')
  
@section('content')
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Buat Pengajuan SKPI Baru</a>
  </div>
</nav>
   
<div class="card">
  <div class="card-body">
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('user.applications.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

      <!-- 2 column grid layout with text inputs for the first and last names -->
      <div class="row mb-4">
        <div class="col">
          <div class="form-outline">
            <input type="text" name="name" value="{{ $user->name }}" id="form6Example1" class="form-control" readonly/>
            <label class="form-label" for="form6Example1">Nama</label>
          </div>
        </div>
        <div class="col">
          <div class="form-outline">
            <input type="text" name="npm" value="{{ $user->npm }}" id="form6Example2" class="form-control" readonly/>
            <label class="form-label" for="form6Example2">NPM</label>
          </div>
        </div>
      </div>

        <table class="table table-bordered" id="dynamicAddRemove">
            <tr>
                <th>Nama Kegiatan</th>
                <th>Klasifikasi</th>
                <th>File Data Dukung</th>
                <th>Aksi</th>
            </tr>
            <tr>
                <td>
                    <!-- <input type="text" name="addMoreInputFields[0][activity]" placeholder="Masukan Nama Kegiatan" class="form-control" /> -->
                    <select name="addMoreInputFields[0][activity]" id="activity_0" onchange="showClassification(0)" class="form-select">
                        <option value="" disabled selected>== Pilih Nama Kegiatan ==</option>
                        @foreach ($activities as $item)
                            <option value="{{ $item['id'] }}">{{ $item['activity'] }}</option>
                        @endforeach
                    </select>
                </td>
                <td>
                    <!-- <input type="text" name="addMoreInputFields[0][classification]" placeholder="Masukan Klasifikasi" class="form-control" /> -->
                    <select name="addMoreInputFields[0][classification]" id="classification_0" class="form-select">
                        <option value="" disabled selected>== Pilih Klasifikasi ==</option>
                    </select>
                </td>
                <td><input type="file" name="addMoreInputFields[0][file]" placeholder="Masukan File Data Dukung" class="form-control" />
                </td>
                <td><button type="button" name="add" id="dynamic-ar" class="btn btn-outline-primary">Tambah</button></td>
            </tr>
        </table>

      <!-- Submit button -->
      <button type="submit" class="btn btn-primary btn-block mb-4">Submit</button>
    </form>
  </div>
</div>

<!-- JavaScript -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript">
    var i = 0;
    $("#dynamic-ar").click(function () {
        ++i;
        $("#dynamicAddRemove").append(
            `<tr>
            <td>
            <select name="addMoreInputFields[${i}][activity]" id="activity_${i}" onchange="showClassification(${i})" class="form-control">
                <option value="">== Pilih Nama Kegiatan ==</option>
                @foreach ($activities as $item)
                    <option value="{{ $item['id'] }}">{{ $item['activity'] }}</option>
                @endforeach
            </select>
            </td>
            <td>
            <select name="addMoreInputFields[${i}][classification]" id="classification_${i}" class="form-control">
                <option value="">== Pilih Klasifikasi ==</option>
            </select>    
            </td>
            <td><input type="file" name="addMoreInputFields[${i}][file]" placeholder="Masukan File Data Dukung" class="form-control" /></td>
            <td><button type="button" class="btn btn-outline-danger remove-input-field">Hapus</button></td>
            </tr>`
            );
    });
    $(document).on('click', '.remove-input-field', function () {
        $(this).parents('tr').remove();
    });

    $(function () {
        $.ajaxSetup({
            headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') }
        });

        $('#activitys').on('change', function () {
            $.ajax({
                url: '{{ route('user.get-classification.data') }}',
                method: 'POST',
                data: {
                    _token: "{{ csrf_token() }}",
                    id: $(this).val()
                },
                success: function (response) {
                    $('#classification').empty();

                    $.each(response, function (index) {
                        $('#classification').append(new Option(response[index].classification, response[index].id))
                    })
                }
            })
            // axios.post('{{ route('user.get-classification.data') }}', {id: $(this).val()})
            // .then(function (response) {
            //     $('#classification').empty();

            //     $.each(response.data, function (id, name) {
            //         $('#classification').append(new Option(name, id))
            //     })
            // });
            
        });
    });
</script>
<script>
function showClassification(code) {
    $.ajax({
        url: '{{ route('user.get-classification.data') }}',
        method: 'POST',
        data: {
            _token: "{{ csrf_token() }}",
            id: $(`#activity_${code}`).val()
        },
        success: function (response) {
            $(`#classification_${code}`).empty();
            $.each(response, function (index) {
                $(`#classification_${code}`).append(new Option(response[index].classification, response[index].id))
            })
        }
    })
}
</script>
@endsection

resources/views/applications/edit.blade.php
@extends('applications.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Pengajuan SKPI</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('user.applications.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('user.applications.update',$application->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <!-- <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $application->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <textarea class="form-control" style="height:150px" name="detail" placeholder="Detail">{{ $application->detail }}</textarea>
                </div>
            </div> -->
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/applications/index.blade.php
@extends('applications.layout')
 
@section('content')
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Pengajuan SKPI Anda</a>
  </div>
</nav>

<div class="card">
    <div class="card-body">   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>User</th>
            <th>BEM</th>
            <th>Dekanat</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($applications as $application)
        <tr>
            <th>{{ ++$i }}</th>
            <td>{{ $application->name }}</td>
            <td>
            @if ($application->bem_confirmed == 1)
                <i class="fas fa-check"></i>
            @elseif ($application->bem_confirmed == 0)
                <i class="fas fa-clock"></i>
            @else
                <i class="fas fa-times"></i>
            @endif
            </td>
            <td>
            @if ($application->dekanat_confirmed == 1)
                <i class="fas fa-check"></i>
            @elseif ($application->dekanat_confirmed == 0)
                <i class="fas fa-clock"></i>
            @else
                <i class="fas fa-times"></i>
            @endif
            </td>
            <td>
                <form action="{{ route('user.applications.destroy',$application->id) }}" method="POST">

                    @if ($application->bem_confirmed == 1 && $application->dekanat_confirmed == 1)
                        <a class="btn btn-info" href="{{ route('user.print_pdf', $application) }}" target="_blank">Print</a>
                    @else
                        <button class="btn btn-light" disabled>Print</button>
                    @endif
                    <!-- <a class="btn btn-info" href="{{ route('user.applications.show',$application->id) }}">Show</a> -->
    
                    <!-- <a class="btn btn-primary" href="{{ route('user.applications.edit',$application->id) }}">Edit</a> -->
   
                    @csrf
                    <!-- @method('DELETE') -->
      
                    <!-- <button type="submit" class="btn btn-danger">Delete</button> -->
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
    {!! $applications->links("pagination::bootstrap-4") !!}

    </div>
</div>

@endsection

resources/views/applications/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pengajuan</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <!-- Font Awesome -->
        <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <link href="{{asset('css/styles.css')}}" rel="stylesheet" />
    
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
      rel="stylesheet"
    />

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&display=swap" rel="stylesheet">
    />
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed" style="background-color: #eee;
    background-image:url({{asset('/images/bgdashboard.png')}});
    background-attachment: fixed;
    background-repeat: no-repeat;
    background-position: bottom right; 
    background-size: contain;">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-blues">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="index.html">SKPI KEMAFAR</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <div class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            </div>
            <!-- Navbar-->
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{{ route('user.profile.edit') }}">Edit Profil</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark bg-blues"  style="background-color: #0a446b; " id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Beranda</div>
                            <a class="nav-link" href="{{ route('user.dashboard') }}">
                                <div class="sb-nav-link-icon"><i class="fas fa-home"></i></div>
                                Beranda
                            </a>
                            <div class="sb-sidenav-menu-heading">Pengajuan</div>
                            <a class="nav-link" href="{{ route('user.applications.index') }}">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                Daftar Pengajuan
                            </a>
                            <a class="nav-link" href="{{ route('user.applications.create') }}">
                                <div class="sb-nav-link-icon"><i class="fas fa-plus-circle"></i></div>
                                Pengajuan Baru
                                </a>
                            <div class="sb-sidenav-menu-heading">Profil</div>
                            <a class="nav-link" href="{{ route('user.profile.edit') }}">
                                <div class="sb-nav-link-icon"><i class="fas fa-user-circle"></i></div>
                                Edit Profil
                            </a>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer" style="background-color: #0f5381;">
                        <div class="small">Login sebagai:</div>
                        {{ Auth::user()->name }}
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid px-4">
                        <div class="container">
                            @yield('content')
                        </div>
                    </div>
                </main>
                <!-- <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2021</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer> -->
            </div>
        </div>
        <script src="{{asset('js/scripts.js')}}"></script>
        <!-- <script src="js/datatables-simple-demo.js"></script> -->
    </body>
</html>

<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
></script>
</body>
</html>

resources/views/applications/show.blade.php
@extends('applications.layout')
  
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Detail Pengajuan SKPI</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('user.applications.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nama:</strong>
                {{ $application->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Konfirmasi BEM:</strong>
                {{ $application->bem_confirmed }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Konfirmasi Dekanat:</strong>
                {{ $application->dekanat_confirmed }}
            </div>
        </div>
    </div>
@endsection

resources/views/applications/skpi_pdf.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Surat Keterangan Pendamping Ijazah</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<style type="text/css">
		table tr td,
		table tr th{
			font-size: 9pt;
		}
	</style>
	<center>
		<h5>Surat Keterangan Pendamping Ijazah</h4>
		<h6><a target="_blank" href="#">Kemafar Unpad</a></h5>
	</center>
	
	<strong>Nama:</strong>
  <p>{{ $application->name }}</p>

	<strong>NPM:</strong>
  <p>{{ $application->npm }}</p>

	<strong>Konfirmasi BEM:</strong>
	@if ($application->bem_confirmed == 1)
      <p>Disetujui</p>
  @elseif ($application->bem_confirmed == 0)
      <p>Pending</p>
  @else
      <p>Ditolak</p>
  @endif

	<strong>Konfirmasi Dekanat:</strong>
	@if ($application->dekanat_confirmed == 1)
      <p>Disetujui</p>
  @elseif ($application->dekanat_confirmed == 0)
      <p>Pending</p>
  @else
      <p>Ditolak</p>
  @endif

	<table class='table table-bordered'>
		<thead>
			<tr>
        <th>No</th>
        <th>Aktivitas</th>
        <th>Klasifikasi</th>
			</tr>
		</thead>
		<tbody>
		@php $i=1 @endphp
		@foreach ($support_datas as $item)
			<tr>
				<td>{{$i++}}</td>
				<td>{{$item->activity }}</td>
        <td>{{ $item->classification }}</td>
			</tr>
			@endforeach
		</tbody>
	</table>

	

</body>
</html>